### ISSUE TITLE
Defining the ExplicitHashKey for a Kinesis Sink

### ISSUE THREAD

**Issue by ttrankle** [awslabs/spark-sql-kinesis-connector#23]
The current configuration around the KPL allows us to define the `PartitionKey` for the Kinesis Sink. This can be seen in the documentation [here](https://github.com/awslabs/spark-sql-kinesis-connector#using-the-kinesis-sink). However, we are not able to define the `ExplicitHashKey` so that we can control to which shards specific rows are assigned. Currently, we would have to instead make sure a given rows `PartitionKey` mapped with an MD5 hash function generates the correct 128 integer within a given shard range. This process is more complex and ideally we'd like to have something as follows:
```
kinesis
  .selectExpr("CAST(rand() AS STRING) as partitionKey", "CAST(explicitHashKey AS STRING)", "CAST(data AS STRING)").as[(String,String,String)]
  .groupBy("data").count()
  .writeStream
  .format("aws-kinesis")
  .outputMode("append")
  .option("kinesis.region", "us-east-1")
  .option("kinesis.streamName", "sparkSinkTest")
  .option("kinesis.endpointUrl", "https://kinesis.us-east-1.amazonaws.com")
  .option("checkpointLocation", "/path/to/checkpoint")
  .start()
```

This would remove the step of having to make sure the partition key is in the correct shard range if we want to send certain rows to specific shards.

**Comment by hwanghw** [comment]
Changes merged to main branch.  Thanks for your contribution.
