### ISSUE TITLE
Plumb through Record TTL to KPL

### ISSUE THREAD

**Issue by penniman26** [awslabs/spark-sql-kinesis-connector#31]
I'm looking to add an optional arg, record TTL, to plumb [through to the KPL](https://javadoc.io/doc/com.amazonaws/amazon-kinesis-producer/latest/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.html#setRecordTtl-long-). The purpose of this is that I don't want my stream writer to drop any records (by default, it will retry only up to 30 seconds). Would you be open to a PR to plumb this through?

**Comment by hwanghw** [comment]
Changes merged to main branch.  Thanks for your contribution.
