### ISSUE TITLE
Requirements to compile

### ISSUE THREAD

**Issue by hafizmujadidKhalid** [awslabs/spark-sql-kinesis-connector#7]
Hey!
Thanks for making an effort to have a kinesis connector for spark-structured streaming. Please list the Java/Scala requirements to compile this jar file. 

When I execute `mvn clean install -DskipTests`, I get following error:

> error: scala.reflect.internal.FatalError:
>   bad constant pool index: 0 at pos: 48445
>      while compiling: <no file>
>         during phase: globalPhase=<no phase>, enteringPhase=<some phase>
>      library version: version 2.12.17
>     compiler version: version 2.12.17

The public jar file link is also not accessible. I always receive the 
`fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

Is it also possible for you to have public maven dependency available in the central maven repository to reduce the effort to compile? Thanks

**Comment by hwanghw** [comment]
Thanks for bringing up the issue.

I compile the connector with scala 2.12.15 and JDK8

Can you try the public jar file again.  It should be accessible now.

**Comment by hafizmujadidKhalid** [comment]
I am still receiving same 403 error code

**Comment by hwanghw** [comment]
hmm. Can you download using this link?
https://awslabs-code-us-east-1.s3.amazonaws.com/spark-sql-kinesis-connector/spark-streaming-sql-kinesis-connector_2.12-1.0.0.jar

**Comment by hafizmujadidKhalid** [comment]
Thanks, i could download using above link.
